# 6. Comparación de sin(x) y cos(x)
x = np.linspace(0, 2*np.pi, 200)
plt.figure()
plt.plot(x, np.sin(x), label='sin(x)')
plt.plot(x, np.cos(x), label='cos(x)', linestyle='--')
plt.title('Comparación sin(x) vs cos(x)')
plt.xlabel('x')
plt.legend()
plt.grid(True)
plt.show()
